#ifndef IMG_CAR_DOWN_YELLOW_DEAD_BITMAP_H
#define IMG_CAR_DOWN_YELLOW_DEAD_BITMAP_H
extern const unsigned short img_car_down_yellow_dead[512];
#define IMG_CAR_DOWN_YELLOW_DEAD_WIDTH 16
#define IMG_CAR_DOWN_YELLOW_DEAD_HEIGHT 32
#endif